### ISSUE TITLE
Possible to build with JNI enabled?

### ISSUE THREAD

**Issue by craigraw** [ShadowsocksR-Live/zbar#3]
As per the title - is is possible to change the build so the `java` directory is included?

**Comment by ssrlive** [comment]
This zbar project has dead. If you want to use QRcode scanner in Android, you can use my other project.
https://github.com/ssrlive/zxing-android

**Comment by craigraw** [comment]
Thanks for your reply. It turns out that zxing is poorer than zbar at scanning QR codes in less than ideal circumstances, such as poor camera quality/blurry images. I managed to get zbar compiled for Windows using your project, and now can scan with both zxing and zbar.

**Comment by ssrlive** [comment]
I have discovered another issue with zbar. When we perform pixel inversion on a QR code image (for example, swapping black and white colors, which is common in text-based QR code graphics where color inversion occurs when you select the text), zbar is unable to recognize it, while zxing can identify it correctly. Can you provide a patch for zbar?

**Comment by craigraw** [comment]
I find both zxing and zbar are unable to find inverted QRs, so as an additional scan I invert the image itself before passing to either reader.

**Comment by ssrlive** [comment]
I was mistaken. iPhones can scan QR codes that are inverted in black and white. this is a text example. the iphone can recognized both. but zbar can recognized the second. it's sad.

```
~# qrencode -t UTF8 'Hello World!' | cat
█████████████████████████████
█████████████████████████████
████ ▄▄▄▄▄ █▀▄█▀▄█ ▄▄▄▄▄ ████
████ █   █ █▀▄█▀██ █   █ ████
████ █▄▄▄█ █▀▀ ▄ █ █▄▄▄█ ████
████▄▄▄▄▄▄▄█▄█ ▀ █▄▄▄▄▄▄▄████
████     █▄ ▄ ██  ▀ ▀ ▀▄▀████
████▄██▄▀█▄█ █▀▄█ ▄█▀  ▄█████
████▄▄█▄▄▄▄▄▀▄ ▄▀▄▄██▀██▄████
████ ▄▄▄▄▄ █▄ ▀▀ ▀▄▀█▀ ▄█████
████ █   █ █ ▀██▄▀  ▀▀█▄▄████
████ █▄▄▄█ █  ▄█ ▀█▄▀▀ ██████
████▄▄▄▄▄▄▄█▄▄▄▄▄█▄█▄██▄█████
█████████████████████████████
█████████████████████████████
```

and this is the text is selected 
![image](https://github.com/ShadowsocksR-Live/zbar/assets/30760636/cdc9583f-0109-4d9a-b956-ed995474ec56)
